#!/usr/bin/env bash
# Sign + notarise + staple the PixlPut release `.app`.
#
# This script REQUIRES the following (none of which exist at v0.1.0 — they are
# the human-handoff items from the final report):
#
#   1. A Developer ID Application certificate in the local keychain.
#      Check with: security find-identity -p codesigning -v
#
#   2. An App-Specific Password stored in keychain via:
#      xcrun notarytool store-credentials AC_PASSWORD \
#          --apple-id "your.appleid@example.com" \
#          --team-id "ABCDE12345"
#
#   3. The Sparkle EdDSA private key generated by Sparkle's `generate_keys`,
#      stored at SPARKLE_PRIVATE_KEY (path or env var). Public key already in
#      Resources/Info.plist as SUPublicEDKey.
#
#   4. A Sparkle appcast URL that the SUFeedURL key in Info.plist points to.
#
# Usage:
#   IDENTITY="Developer ID Application: Your Name (ABCDE12345)" \
#   KEYCHAIN_PROFILE="AC_PASSWORD" \
#   ./scripts/release-app.sh
#
# WHAT THIS SCRIPT DOES (when the inputs above are in place):
#   1. `scripts/build-app.sh release`
#   2. codesign --options runtime --entitlements Resources/Entitlements.plist
#   3. ditto -c -k --keepParent build/PixlPut.app build/PixlPut.zip
#   4. xcrun notarytool submit --wait
#   5. xcrun stapler staple build/PixlPut.app
#   6. (optional) sparkle sign_update to produce the EdDSA signature for the appcast

set -euo pipefail

if [[ -z "${IDENTITY:-}" ]]; then
    echo "ERROR: IDENTITY env var required (Developer ID Application identity)." >&2
    echo "       Check available identities: security find-identity -p codesigning -v" >&2
    exit 1
fi
if [[ -z "${KEYCHAIN_PROFILE:-}" ]]; then
    echo "ERROR: KEYCHAIN_PROFILE env var required (xcrun notarytool keychain profile name)." >&2
    exit 1
fi

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
APP_BUNDLE="${ROOT}/build/PixlPut.app"
ENT="${ROOT}/Resources/Entitlements.plist"
ZIP="${ROOT}/build/PixlPut.zip"

"${ROOT}/scripts/build-app.sh" release

echo "==> codesign (inside-out, hardened runtime on every executable)"
# NOT --deep: it can't apply per-artifact options and breaks Sparkle's nested
# signatures on the first update attempt. Notarization requires the hardened
# runtime on EVERY nested executable, so sign inside-out explicitly.
SPARKLE_FW="${APP_BUNDLE}/Contents/Frameworks/Sparkle.framework"
if [[ -d "${SPARKLE_FW}" ]]; then
    for xpc in "${SPARKLE_FW}/Versions/B/XPCServices/"*.xpc; do
        codesign --force --options runtime --sign "${IDENTITY}" "${xpc}"
    done
    codesign --force --options runtime --sign "${IDENTITY}" \
        "${SPARKLE_FW}/Versions/B/Autoupdate"
    codesign --force --options runtime --sign "${IDENTITY}" \
        "${SPARKLE_FW}/Versions/B/Updater.app"
    codesign --force --options runtime --sign "${IDENTITY}" "${SPARKLE_FW}"
fi
codesign --force --options runtime \
    --entitlements "${ENT}" \
    --sign "${IDENTITY}" \
    "${APP_BUNDLE}"
codesign --verify --strict --deep --verbose=2 "${APP_BUNDLE}"

echo "==> zip for notarisation submission"
rm -f "${ZIP}"
ditto -c -k --keepParent "${APP_BUNDLE}" "${ZIP}"

echo "==> xcrun notarytool submit --wait"
xcrun notarytool submit "${ZIP}" \
    --keychain-profile "${KEYCHAIN_PROFILE}" \
    --wait

echo "==> xcrun stapler staple"
xcrun stapler staple "${APP_BUNDLE}"
xcrun stapler validate "${APP_BUNDLE}"

echo
echo "==> release-ready: ${APP_BUNDLE}"
echo
echo "Sparkle next steps (manual):"
echo "  - sign_update -f <SPARKLE_PRIVATE_KEY> ${ZIP}  # produces sparkle:edSignature"
echo "  - Update appcast.xml with the new <enclosure> + sparkle:edSignature"
echo "  - Upload PixlPut.zip + appcast.xml to the host pointed at by SUFeedURL"
